### PR TITLE
Use dispatch instead of manual branching

### PR DESCRIPTION
**Pull request by Tortar**
Hi @mastrof, how is it going? This is just to let you know about this new possibility in MixedStructTypes :-)

### CODE REVIEW

**Comment by mastrof** [comment]
Hey :) Microbes are keeping me busy in the lab, but I have a few projects going that will finally make good use of this library. 

Yes I had a quick look at MixedStructTypes and adopted it immediately, great job!
I had actually used `@dispatch` initially but I think Julia was complaining during precompilation. Can't recall exactly, I think it was just a warning that it could not precompile the function. I did not look at the internals but I guess it's sort of expected if the macro tries to "rewrite" the function during package compilation. Everything was still working as expected ofc but I was on a bit of a rush and went for the least effort path, so just used branching instead to avoid the warning. If you load the library using the `@dispatch`-ed function I think you'll get the same warning. If not I'll check again

**Comment by Tortar** [comment]
simulated microbes clearly require less work ahah. 

I find this package rather interesting anyway, have you thought on making an announcement on discourse? Maybe someone will show up to help you, unfortunately I'm not a biology guy so I can't :D

Anyway, thanks for letting me know of the issue! Indeed I tried to dev this branch and it is as you say :(
Fortunately, I have some tricks under my belt to tackle this, so hopefully as soon as I find the time, this shoud be solved.

**Comment by Tortar** [comment]
Hi @mastrof, I released a new renamed version of the package which also solved this issue, now it should work fine!

**Comment by Tortar** [comment]
mmmh, not sure why is it failing, because everything works fine locally

**Comment by Tortar** [comment]
Could you run the workflow again?

**Pull request merged**
